name: CI

on:
  push:

permissions:
  contents: read

jobs:
  quality-checks:
    name: Testes e lint
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Instalar dependências
        run: uv sync --locked

      - name: Executar testes
        run: uv run pytest

      - name: Executar lint
        run: uv run ruff check .
